export type Authority = {
  id: string;
  name: string;
  note: string;
  central?: boolean;
};

export const AUTHORITIES: Authority[] = [
  {
    id: "bcc",
    name: "Bengaluru Central City Corporation",
    note: "Ward-level roads, drains, garbage, street lights (Central)",
  },
  {
    id: "bec",
    name: "Bengaluru East City Corporation",
    note: "Ward-level civic works (East)",
  },
  {
    id: "bwc",
    name: "Bengaluru West City Corporation",
    note: "Ward-level civic works (West)",
  },
  {
    id: "bnc",
    name: "Bengaluru North City Corporation",
    note: "Ward-level civic works (North)",
  },
  {
    id: "bsc",
    name: "Bengaluru South City Corporation",
    note: "Ward-level civic works (South)",
  },
  {
    id: "gba",
    name: "Greater Bengaluru Authority",
    note: "Apex body — planning, arterial roads, cross-corporation projects",
  },
  { id: "bwssb", name: "BWSSB", note: "Water supply and sewage" },
  { id: "bescom", name: "BESCOM", note: "Electricity supply, transformers, billing" },
  { id: "bmrcl", name: "BMRCL", note: "Namma Metro construction and operations" },
  { id: "bda", name: "BDA", note: "Layouts, sites, development schemes" },
  { id: "other", name: "Other — enter authority manually", note: "Any other Karnataka public authority" },
];

/**
 * Ward reference list — the full GBA dataset: 369 wards across five
 * corporations, generated from the official ward boundary GeoJSON.
 */
export type { Ward } from "./wards";
export { WARDS } from "./wards";


/** Verified legal constants — never generated by a model. */
export const LEGAL = {
  fee: "₹10 application fee (Karnataka). BPL applicants are exempt on producing a copy of the BPL card.",
  copyCharges: "₹2 per A4 page for copies of records.",
  paymentModes: [
    "Online via the Karnataka RTI portal (SBI e-Pay)",
    "Indian Postal Order (IPO) — the safest fallback",
    "Demand Draft",
    "Court-fee stamp — valid in Karnataka, never for central-government RTIs",
  ],
  portal: "rtionline.karnataka.gov.in",
  portalCaveat:
    "The Karnataka portal covers Karnataka state public authorities only. Do not use it for central bodies.",
  pioDays: 30,
  lifeLibertyHours: 48,
  firstAppealWindowDays: 30,
  faaDecisionDays: 30,
  faaMaxDays: 45,
  secondAppealWindowDays: 90,
  secondAppealAfterDays: 45,
  ksicAddress:
    "Karnataka State Information Commission, Room No. 305, 3rd Floor, M S Building, Bengaluru 560001",
  section62:
    "Section 6(2): you cannot be asked to give a reason for wanting the information. Never state one.",
  section18:
    "A Section 18 complaint to the Information Commission has no time limit — use it if you have missed an appeal window.",
  calendarDays: "All periods are calendar days, including weekends and public holidays.",
};

export const STATUS_LABEL: Record<string, string> = {
  draft: "Draft",
  filed: "Filed",
  replied: "Replied",
  first_appeal_filed: "First appeal filed",
  second_appeal_filed: "Second appeal filed",
  closed: "Closed",
};

export function daysBetween(from: string | Date, to: string | Date = new Date()): number {
  const a = new Date(typeof from === "string" ? `${from}T00:00:00` : from);
  const b = new Date(typeof to === "string" ? `${to}T00:00:00` : to);
  return Math.floor((b.getTime() - a.getTime()) / 86_400_000);
}

export function addDays(date: string | Date, days: number): string {
  const d = new Date(typeof date === "string" ? `${date}T00:00:00` : date);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

export function today(): string {
  return new Date().toISOString().slice(0, 10);
}

export type Clock = {
  label: string;
  tone: "calm" | "warn" | "danger" | "neutral";
  urgency: number;
};

/** Live statutory clock for an application row. */
export function clockFor(
  app: {
    status: string;
    filed_date: string | null;
    response_due_date: string | null;
    reply_received_date: string | null;
  },
  appeals?: { tier: string; filed_date: string | null }[],
): Clock {
  if (app.status === "draft") return { label: "Not filed yet", tone: "neutral", urgency: 10 };
  if (app.status === "closed") return { label: "Closed", tone: "neutral", urgency: 90 };
  if (app.status === "replied") {
    const d = app.reply_received_date ? daysBetween(app.reply_received_date) : 0;
    const left = LEGAL.firstAppealWindowDays - d;
    return left > 0
      ? { label: `Replied — ${left} days left to appeal`, tone: "warn", urgency: 3 }
      : { label: "Replied — appeal window closed (Section 18 still open)", tone: "neutral", urgency: 40 };
  }
  if (app.status === "first_appeal_filed") {
    const first = (appeals ?? []).find((a) => a.tier === "first" && a.filed_date);
    const hasSecond = (appeals ?? []).some((a) => a.tier === "second");
    if (first?.filed_date) {
      const faaSilentDays = daysBetween(first.filed_date);
      if (faaSilentDays >= LEGAL.secondAppealAfterDays && !hasSecond) {
        return {
          label: `Second appeal available — FAA silent ${faaSilentDays} days`,
          tone: "danger",
          urgency: 0,
        };
      }
      return {
        label: `First appeal filed — FAA has ${LEGAL.faaMaxDays - faaSilentDays} days left`,
        tone: "warn",
        urgency: 2,
      };
    }
    return { label: STATUS_LABEL[app.status] ?? app.status, tone: "warn", urgency: 4 };
  }
  if (app.status === "second_appeal_filed") {
    return { label: STATUS_LABEL[app.status] ?? app.status, tone: "warn", urgency: 4 };
  }
  if (app.filed_date) {
    const day = daysBetween(app.filed_date);
    if (day > LEGAL.pioDays) {
      return {
        label: `Overdue by ${day - LEGAL.pioDays} days — first appeal available`,
        tone: "danger",
        urgency: 0,
      };
    }
    return {
      label: `Day ${day} of ${LEGAL.pioDays}`,
      tone: day >= 25 ? "warn" : "calm",
      urgency: day >= 25 ? 1 : 20 - day / 100,
    };
  }
  return { label: "Filed", tone: "calm", urgency: 30 };
}
