export type Authority = {
  id: string;
  name: string;
  note: string;
  central?: boolean;
};

export const AUTHORITIES: Authority[] = [
  {
    id: "bcc",
    name: "Bengaluru Central City Corporation",
    note: "Ward-level roads, drains, garbage, street lights (Central)",
  },
  {
    id: "bec",
    name: "Bengaluru East City Corporation",
    note: "Ward-level civic works (East)",
  },
  {
    id: "bwc",
    name: "Bengaluru West City Corporation",
    note: "Ward-level civic works (West)",
  },
  {
    id: "bnc",
    name: "Bengaluru North City Corporation",
    note: "Ward-level civic works (North)",
  },
  {
    id: "bsc",
    name: "Bengaluru South City Corporation",
    note: "Ward-level civic works (South)",
  },
  {
    id: "gba",
    name: "Greater Bengaluru Authority",
    note: "Apex body — planning, arterial roads, cross-corporation projects",
  },
  { id: "bwssb", name: "BWSSB", note: "Water supply and sewage" },
  { id: "bescom", name: "BESCOM", note: "Electricity supply, transformers, billing" },
  { id: "bmrcl", name: "BMRCL", note: "Namma Metro construction and operations" },
  { id: "bda", name: "BDA", note: "Layouts, sites, development schemes" },
  { id: "other", name: "Other — enter authority manually", note: "Any other Karnataka public authority" },
];

/**
 * Ward reference list — the full GBA dataset: 369 wards across five
 * corporations, generated from the official ward boundary GeoJSON.
 */
export type { Ward } from "./wards";
export { WARDS } from "./wards";


/** Verified legal constants — never generated by a model. */
export const LEGAL = {
  fee: "Rs. 10 application fee (Karnataka). BPL applicants are exempt on producing a copy of the BPL card.",
  copyCharges: "Rs. 2 per A4 page for copies of records.",
  onlinePaymentModes: [
    "Netbanking",
    "Debit or credit card",
    "BHIM UPI",
  ],
  onlinePaymentNote:
    "Paid through the Government of Karnataka Khajane-II gateway, via ICICI e-Pay or SBI e-Pay as the aggregator.",
  postalPaymentModes: [
    "Indian Postal Order (IPO) - accepted everywhere, the safest fallback",
    "Demand Draft",
    "Court-fee stamp - valid in Karnataka, never for central-government RTIs",
  ],

  portal: "rtionline.karnataka.gov.in",
  portalCaveat:
    "The Karnataka portal covers Karnataka state public authorities only. Do not use it for central bodies.",
  pioDays: 30,
  lifeLibertyHours: 48,
  firstAppealWindowDays: 30,
  faaDecisionDays: 30,
  faaMaxDays: 45,
  secondAppealWindowDays: 90,
  secondAppealAfterDays: 45,
  ksicAddress:
    "Karnataka State Information Commission, Room No. 305, 3rd Floor, M S Building, Bengaluru 560001",
  section62:
    "Section 6(2): you cannot be asked to give a reason for wanting the information. Never state one.",
  section18:
    "A Section 18 complaint to the Information Commission has no time limit — use it if you have missed an appeal window.",
  calendarDays: "All periods are calendar days, including weekends and public holidays.",
  rule14:
    "Karnataka Rule 14: one subject matter per application, and ordinarily no more than 150 words. Multiple subjects mean the PIO may answer only the first.",
};

/** Word budget under Rule 14 (soft cap — the rule says "ordinarily"). */
export const RULE14_WORD_LIMIT = 150;

export function countWords(text: string): number {
  return text.trim() ? text.trim().split(/\s+/).length : 0;
}

/**
 * Exact public-authority strings as they appear on rtionline.karnataka.gov.in.
 * The portal still lists Bengaluru under the nine legacy BBMP zones, not the
 * five GBA city corporations. Reproduced verbatim, spacing and spellings included.
 */
export const PORTAL_AUTHORITIES = {
  bbmpZones: [
    "Bruhat Bengaluru Mahanagara Palike (West Zone)BBMP",
    "Bruhat Bengaluru Mahanagara Palike (South Zone)BBMP",
    "Bruhat Bengaluru Mahanagara Palike (Dasarahalli Zone)BBMP",
    "Bruhat Bengaluru Mahanagara Palike (Raja rajeshwarinagar Zone)BBMP",
    "Bruhat Bengaluru Mahanagara Palike (Central Zone) BBMP",
    "Bruhat Bengaluru Mahanagara Palike (East Zone) BBMP",
    "Bruhat Bengaluru Mahanagara Palike (Bommanahalli Zone) BBMP",
    "Bruhat Bengaluru Mahanagara Palike (Mahadevapura Zone) BBMP",
    "Bruhat Bengaluru Mahanagara Palike (Yalahanka Zone) BBMP",
  ],
  bwssbUnits: [
    "Bangalore water supply and sewage board(Administration)",
    "Bangalore water supply and sewage board(Finance)",
    "Bangalore water supply and sewage board(East)",
    "Bangalore water supply and sewage board(West)",
    "Bangalore Water Supply And Sewerage Board (North)",
    "Bangalore Water Supply And Sewerage Board (South)",
    "Bangalore water supply and sewage board(Design)",
    "Bangalore water supply and sewage board(Kaveri Project)",
    "Bangalore Water Supply And Sewerage Board (Kaveri Operation And Maintenance)",
    "Bangalore water supply and sewage board(WWM) - East",
    "Bangalore Water Supply And Sewerage Board(WWM) - West",
    "Bangalore water supply and sewage board(WWM-110V)",
  ],
  bescom: "Bangalore Electricity Supply Company Ltd (BESCOM)",
} as const;

/**
 * Only four GBA zones have a verified equivalent in the portal's BBMP zone list.
 * The other six (C.V. Raman Nagar, Gandhinagara, K.R. Pura, Byatarayanapura,
 * Jayanagar, Malleshwaram) have none — never guess, ask the user.
 */
const GBA_ZONE_TO_PORTAL: Record<string, string> = {
  Mahadevapura: "Bruhat Bengaluru Mahanagara Palike (Mahadevapura Zone) BBMP",
  Yelahanka: "Bruhat Bengaluru Mahanagara Palike (Yalahanka Zone) BBMP",
  Bommanahalli: "Bruhat Bengaluru Mahanagara Palike (Bommanahalli Zone) BBMP",
  Rajarajeshwarinagar:
    "Bruhat Bengaluru Mahanagara Palike (Raja rajeshwarinagar Zone)BBMP",
};

export function portalZoneForGbaZone(zone: string | null | undefined): string | null {
  if (!zone) return null;
  return GBA_ZONE_TO_PORTAL[zone.trim()] ?? null;
}

export type PortalAuthorityKind = "bbmp" | "bwssb" | "bescom" | "none";

/** Which portal picker applies to a saved application's public authority. */
export function portalAuthorityKind(authority: string): PortalAuthorityKind {
  const a = authority.toLowerCase();
  if (a.includes("bwssb") || a.includes("water supply")) return "bwssb";
  if (a.includes("bescom") || a.includes("electricity")) return "bescom";
  if (a.includes("corporation") || a.includes("bbmp") || a.includes("bengaluru authority"))
    return "bbmp";
  return "none";
}


export const STATUS_LABEL: Record<string, string> = {
  draft: "Draft",
  filed: "Filed",
  replied: "Replied",
  first_appeal_filed: "First appeal filed",
  second_appeal_filed: "Second appeal filed",
  closed: "Closed",
};

export function daysBetween(from: string | Date, to: string | Date = new Date()): number {
  const a = new Date(typeof from === "string" ? `${from}T00:00:00` : from);
  const b = new Date(typeof to === "string" ? `${to}T00:00:00` : to);
  return Math.floor((b.getTime() - a.getTime()) / 86_400_000);
}

export function addDays(date: string | Date, days: number): string {
  const d = new Date(typeof date === "string" ? `${date}T00:00:00` : date);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

export function today(): string {
  return new Date().toISOString().slice(0, 10);
}

/**
 * The Karnataka RTI portal restricts the request/appeal text field to
 * A-Z a-z 0-9 and , . - _ ( ) / @ : & \ % ? and caps it at 3000 characters.
 */
export const PORTAL_ALLOWED = /[^A-Za-z0-9 \n,.\-_()\/@:&\\%?]/g;
export const PORTAL_MAX_CHARS = 3000;

export function toPortalSafe(text: string): string {
  return text
    .replace(/₹\s?/g, "Rs. ")
    .replace(/[–—]/g, "-")
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'")
    .replace(/…/g, "...")
    .replace(PORTAL_ALLOWED, "");
}

/** The portal's fixed first-appeal ground dropdown. */
export const APPEAL_GROUNDS = [
  { id: "refused", label: "Access to the requested information was refused" },
  { id: "no_response", label: "No response received within the time limit" },
  { id: "excess_fee", label: "Unreasonable amount of fee demanded" },
  { id: "incomplete", label: "Incomplete, misleading or false information provided" },
  { id: "other", label: "Any other ground" },
] as const;

export function appealGroundLabel(id: string | null | undefined): string | null {
  return APPEAL_GROUNDS.find((g) => g.id === id)?.label ?? null;
}

/** Sub-registration number advisory for split applications. */
export const SPLIT_ADVISORY =
  "If your application was forwarded to more than one PIO, the portal splits it into sub-numbers (e.g. .../60104/1). Each sub-number gets its own reply. File your appeal against the specific sub-number you are dissatisfied with, not the parent number.";


export type Clock = {
  label: string;
  tone: "calm" | "warn" | "danger" | "neutral";
  urgency: number;
};

/** Live statutory clock for an application row. */
export function clockFor(
  app: {
    status: string;
    filed_date: string | null;
    response_due_date: string | null;
    reply_received_date: string | null;
    transfer_date?: string | null;
  },

  appeals?: { tier: string; filed_date: string | null }[],
): Clock {
  if (app.status === "draft") return { label: "Not filed yet", tone: "neutral", urgency: 10 };
  if (app.status === "closed") return { label: "Closed", tone: "neutral", urgency: 90 };
  if (app.status === "replied") {
    const d = app.reply_received_date ? daysBetween(app.reply_received_date) : 0;
    const left = LEGAL.firstAppealWindowDays - d;
    return left > 0
      ? { label: `Replied — ${left} days left to appeal`, tone: "warn", urgency: 3 }
      : { label: "Replied — appeal window closed (Section 18 still open)", tone: "neutral", urgency: 40 };
  }
  if (app.status === "first_appeal_filed") {
    const first = (appeals ?? []).find((a) => a.tier === "first" && a.filed_date);
    const hasSecond = (appeals ?? []).some((a) => a.tier === "second");
    if (first?.filed_date) {
      const faaSilentDays = daysBetween(first.filed_date);
      if (faaSilentDays >= LEGAL.secondAppealAfterDays && !hasSecond) {
        return {
          label: `Second appeal available — FAA silent ${faaSilentDays} days`,
          tone: "danger",
          urgency: 0,
        };
      }
      return {
        label: `First appeal filed — FAA has ${LEGAL.faaMaxDays - faaSilentDays} days left`,
        tone: "warn",
        urgency: 2,
      };
    }
    return { label: STATUS_LABEL[app.status] ?? app.status, tone: "warn", urgency: 4 };
  }
  if (app.status === "second_appeal_filed") {
    return { label: STATUS_LABEL[app.status] ?? app.status, tone: "warn", urgency: 4 };
  }
  if (app.filed_date) {
    const transferred = !!app.transfer_date;
    const day = daysBetween(app.transfer_date ?? app.filed_date);
    if (day > LEGAL.pioDays) {
      return {
        label: `Overdue by ${day - LEGAL.pioDays} days — first appeal available`,
        tone: "danger",
        urgency: 0,
      };
    }
    return {
      label: `Day ${day} of ${LEGAL.pioDays}${transferred ? " (from transfer)" : ""}`,
      tone: day >= 25 ? "warn" : "calm",
      urgency: day >= 25 ? 1 : 20 - day / 100,
    };
  }

  return { label: "Filed", tone: "calm", urgency: 30 };
}
